### ISSUE TITLE
Leaked Threads in HttpRequests

### ISSUE THREAD

**Issue by Matulis** [cloudant/sync-android#108]
I believe the call to: getClientConnectionManager(HttpParams params) seems to be leaking threads. I only noticed this in an application with a large amount of replications occurring.

I know it's more of an Apache issue, but I wanted to bring this up

**Comment by mikerhodes** [comment]
Hmm, no one followed up on this. I think we're addressing this with a move away from the Apache libraries, see https://github.com/cloudant/sync-android/pull/110.
