### ISSUE TITLE
Method to Purge Documents

### ISSUE THREAD

**Issue by Matulis** [cloudant/sync-android#160]
I started work on creating a method to purge documents much like in the CouchDB API, one issue I came across is how the IndexManager should be updated when documents are purged. At this point I was thinking an additional public method to force an index rebuild? Otherwise I believe we would have to add purge sequences to the SQL schema and use that in calls to update all indexes.

**Comment by mikerhodes** [comment]
As a side question, before my answer, what was your purge use-case? I've been collecting these, to back time on our side doing this (though, of course, PRs are very welcome here).

Hmm, yes I can see how purging could spoil indexing given the lack of change in sequence number, if the rows are just dropped from the `revs` table.

On the other hand, all that will happen is that during querying, we get a spurious result which the result iterator will throw away when it can't retrieve the document for.

To force a rebuild, one currently just has to drop and recreate the index -- I'm not sure a rebuild method is necessary?

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/sync-android/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
