### ISSUE TITLE
Ability to traverse the whole rev tree

### ISSUE THREAD

**Issue by nolanlawson** [cloudant/sync-android#170]
In CouchDB and PouchDB, you can traverse the entire rev tree, which is nice if you're not using compaction and want to retain document history. Since this lib doesn't compact by default (or so I was told in IRC), it would be great if we could traverse the rev tree.

**Comment by mikerhodes** [comment]
I'm a little dubious as I'd like to figure out auto-compaction at some point, though whether we'll ever do that is an entire different question :) I also feel using the rev history in this way is somewhat misusing the capability -- and also would break behaviour on Cloudant with the auto-compaction we do there, potentially confusing devs, or even causing "data loss" of old revisions.

**Comment by nolanlawson** [comment]
Yeah it's a weird use-case that I believe in, but I know not everybody agrees with me. :) I even went so far as to write this thing: https://github.com/nolanlawson/pouchdb-full-sync

Being able to disable auto-compaction in Cloudant would be neat as well. TBH I'm kinda sad that that will be the unchangeable default behavior in CouchDB 2.0 as well.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/sync-android/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
