### ISSUE TITLE
_rev id creation is non-deterministic

### ISSUE THREAD

**Issue by Matulis** [cloudant/sync-android#175]
I've run into the issue in a continuously replicating database in which a conflict rises and then the clients create a new revision deterministically when they detect the conflict. Each client hypothetically makes the same changes to the document in conflict, however each version results in a different _rev tag. This can lead to a ping-ponging of changes between clients without ever coming to a convergence. 

According to the CouchDB docs, this _rev should be deterministic(md5-hash of JSON body, attachments, _deleted flag):
http://guide.couchdb.org/draft/conflicts.html#deterministic

I have tested a simple version in which I only consider the md5 hash of the body and the _deleted value, and it seems to have fixed the issue for me. I think if the original algorithm from erlang can be ported and verified then it would be ideal for compatibility with other clients.

**Comment by mikerhodes** [comment]
The rev id generated by CouchDB _happens_ to be deterministic, there isn't a _should_ here; the only requirement is that revision IDs contain sufficient information to differentiate revisions. There are useful properties to consistent rev ids, I admit, but we've not delved into doing this on Android. I'm not against this on principle, however, so would be happy to see PRs with improvements.

It's been discussed before, with respect to PouchDB which generates random revision hashes like the Android Cloudant Sync does: http://markmail.org/thread/r7yskmj5mvg45qdh. In the end, there was no consensus on what an appropriate rev generation algorithm should be https://issues.apache.org/jira/browse/COUCHDB-2338.

**Comment by ricellis** [comment]
See also [this thread](http://mail-archives.apache.org/mod_mbox/couchdb-dev/201603.mbox/%3CCADC7mDLTR1hra8kgd9fC36c=4n84-FA-7eRg5p-khSr4ddp_0w@mail.gmail.com%3E) which discusses some issues with trying to replicate the CouchDB rev hashes and has some talk of developing a common algorithm.
