### ISSUE TITLE
Error:(118, 32) error: DocumentRevision is abstract; cannot be instantiated

### ISSUE THREAD

**Issue by raihan-mpower** [cloudant/sync-android#241]
getting error in tasks model class
The document revision is an interface that it tries to instantiate

**Comment by tomblench** [comment]
@raihan-mpower we are currently re-writing the `DocumentRevision`/`BasicDocumentRevision` classes. You should visit the documentation for our latest tagged release here: https://github.com/cloudant/sync-android/tree/0.15.5

This will explain that you can instantiate `BasicDocumentRevision` classes.

In the near future we will make a release which removes `BasicDocumentRevision` and changes `DocumentRevision` from an interface to a concrete class. Apologies for any confusion.

**Comment by sarabahis** [comment]
When will the new release be?

**Comment by rhyshort** [comment]
Hopefully in the not too distant future, we still have a few things to work through before we release.
