### ISSUE TITLE
Generate method counts

### ISSUE THREAD

**Issue by ricellis** [cloudant/sync-android#271]
We get asked about the method count of the library which is important with the 65k method limit before multidex.
A lot of this goes away in later versions of Android with the newer tool chain, however it would be helpful to have the method count.

**Comment by tomblench** [comment]
Crude method counts are: 
- 1587 methods (our code only)
- 22974 methods (our code plus all dependencies)
This will vary slightly across J2SE/Android but the figures should be a good enough yardstick.

Note that guava accounts for 12279 third-party methods (!)

Counts generated by some home-brew `perl` tooling, but I did a few spot checks and the numbers seem to make sense.

**Comment by tomblench** [comment]
OK so it turns out I was looking at the wrong thing and it's method _references_ we care about.

**Comment by ricellis** [comment]
For the released versions we can get a decent breakdown at [methodscount](http://www.methodscount.com/?lib=com.cloudant%3Acloudant-sync-datastore-core%3A1.0.0).
I've created some gradle tasks that can get us the total count for a WIP.
