### ISSUE TITLE
Boolean query in IndexManager.find method issue

### ISSUE THREAD

**Issue by bensentropy** [cloudant/sync-android#273]
When searching over a Boolean field in documents matching results are not being returned when using the IndexManager.find method.

**Comment by rhyshort** [comment]
Hi thanks for reporting this. Could you provide us with the selector and an example of the documents that should be returned?

**Comment by mtotschnig** [comment]
I am trying to find document
`{"lastName":"McConnell","firstName":"Brandi","favorite":true,"type":"contacts"}`
with the following query
```
final HashMap<String, Object> query = new HashMap<>();
        query.put("favorite", true);
```
and get empty result

**Comment by bensentropy** [comment]
mtotschnig's issue is exactly the same as mine.

**Comment by ricellis** [comment]
Thanks for reporting this, it does indeed look like a bug. I can see that we are indexing `Boolean` fields in the [IndexUpdater here](https://github.com/cloudant/sync-android/blob/master/cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/query/IndexUpdater.java#L329).
However, I can see that when we validate the query we only consider the predicate valid if it is a `String` or a `Number` in the [QueryValidator here](https://github.com/cloudant/sync-android/blob/master/cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/query/QueryValidator.java#L590), so we appear to reject queries using `boolean` fields when we should not.

As an aside it also looks like we also try to index `Byte` and `byte[]`, which I don't think are valid in JSON documents so we can probably remove those types from `IndexUpdater#populateDBParameter`.

**Comment by rhyshort** [comment]
This looks like it was caused by misunderstanding the intent of the Objc code that was being ported from [CDTDatastore here](https://github.com/cloudant/CDTDatastore/blob/master/CDTDatastore/query/CDTQQueryValidator.m#L522)

@ricellis Have you raised an issue for the `Byte` and `byte[]`?

**Comment by ricellis** [comment]
I was expecting it to be fixed under this issue also, along with additional query tests for all of the types that are indexed (if we don't currently have them). @rhyshort I have a test for boolean if you want it.

**Comment by rhyshort** [comment]
`byte` indexing and querying works, (the validator doesn't exclude those) `byte[]` as expected doesn't, a byte[] although a java primitive is valid in our JSON docs ( I think this is due to jackson being able to deserialise to an array or a list for JSON arrays).`byte[]` cannot be used in queries in with the `$in`. Will continue digging.

**Comment by rhyshort** [comment]
We only accept lists in Query selectors, a `byte[]`, I think we can leave things as they are, w.r.t. that.
