### ISSUE TITLE
Small attachments unnecessarily base64 encoded

### ISSUE THREAD

**Issue by ricellis** [cloudant/sync-android#276]
In com.cloudant.sync.datastore.RevisionHistoryHelper#addAttachments the attachments are checked 1 at a time and inline attachments are always base64 encoded. However, in a mixture of large and small attachments where the attachments will be sent as part of a MIME multipart/related message it does not make sense to do this base64 encoding.

We should perform an initial check of the attachments to identify if any attachment revisions that need to be sent qualify for multipart and if so all attachments should be done as multipart.

**Comment by tomblench** [comment]
Done in #311
