### ISSUE TITLE
Perform readability validation on JavaSE also

### ISSUE THREAD

**Issue by ricellis** [cloudant/sync-android#292]
The validation that a database has been correctly opened is currently only performed on Android. We should do this on JavaSE as well.
See com.cloudant.sync.sqlite.SQLDatabaseFactory#validateOpenedDatabase

Currently doing so causes failures, particularly in IndexUpdater tests, which I anticipate may be resolved by #286.
I think it is safe to do the validation on the `SQLDatabase` and not the `SQLDatabaseQueue` because it happens before it is returned for other access.

**Comment by tomblench** [comment]
NB: `validateOpenedDatabase` is only called for the SQLCipher case of `openSqlDatabase`

**Comment by ricellis** [comment]
I believe the validation was originally added to verify the supplied key was appropriate to read the database in the encrypted case, but I don't think there is anything to stop us running it in all cases if we feel that it is valuable to do so.

**Comment by tomblench** [comment]
Note that `validateOpenedDatabase` appears not to exist any more, probably was lost some time around #501
