### ISSUE TITLE
Replication test for a shared database

### ISSUE THREAD

**Issue by ricellis** [cloudant/sync-android#293]
We should validate that replication runs successfully when using a Cloudant shared database as a target.

**Comment by tomblench** [comment]
See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mobile-couchbase/6Vc1ZQLclwc/bB_RQcfrBQAJ for more details

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/sync-android/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
