### ISSUE TITLE
Create entire storage path if it does not already exist

### ISSUE THREAD

**Issue by ricellis** [cloudant/sync-android#294]
Initializing a `DatastoreManager` currently creates only a single directory of the path by calling `directoryPath.mkdir();` if it doesn't exist.
It would be nicer to create any necessary parent directories too by calling `mkdirs()`.
We should document the behaviour and the exceptions that could be thrown if it is not possible to create the paths.

**Comment by rhyshort** [comment]
Done in cbe43c0
