### ISSUE TITLE
Reduce code duplication in QuerySQLTranslator

### ISSUE THREAD

**Issue by rhyshort** [cloudant/sync-android#302]
QuerySQLTranslator has a lot of duplicated code, these should be replaced with method calls to do the right thing

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/sync-android/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
