### ISSUE TITLE
Add availability check for Enhanced Query Syntax

### ISSUE THREAD

**Issue by ricellis** [cloudant/sync-android#304]
Look into adding a check to allow for the developer to see if Enhanced Query Syntax is enabled. For Android we probably can't find this out easily. One option may be to populate the temporary `VIRTUAL` table that we use to check for FTS availability and perform a query that contains enhanced query syntax (perhaps the `NOT` operator) and check the result to see if it worked.

**Comment by rhyshort** [comment]
Our test code currently has conditions that check for this. We could make the check a method on the datastore. See `SQLDatabaseTestUtils.getCompileOptions` the test we currently use `compileOptions.containsAll(Arrays.asList("ENABLE_FTS3", "ENABLE_FTS3_PARENTHESIS"))`

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/sync-android/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
