### ISSUE TITLE
Refactor indexing code

### ISSUE THREAD

**Issue by ricellis** [cloudant/sync-android#305]
Refactoring the `Index` class code as well as code in the `IndexManager`, `IndexCreator`, and the `IndexUpdater` to better utilize the `Index` class.  The `Index` class needs to be decoupled from the other classes and be able to stand on its own.  We will look to:
1.  Implement as `Comparable` and utilize the `compareTo` method interface.
2.  ~~Possibly implement `IndexType` as an enumeration.~~ Done
3.  Refactor code blocks in the `IndexManager`, `IndexCreator`, and `IndexUpdater` that currently handle indexes as `Map<String, Object>` and instead solely deal with an index as an `Index` object.

@rhyshort FYI

**Comment by rhyshort** [comment]
4. Make sure any newly public class are marked as API private in the doc annotations.

**Comment by tomblench** [comment]
Change API methods to be more logical and consistent. Instead of all the different `ensureIndexed` we should have:

```java
ensureIndexed(List<FieldSort> fieldNames, String indexName, IndexType indexType, String tokenize)
```

- If the user wants an auto-generated name, set `indexName` `null`
- If the user is creating a JSON index, `tokenize` should be `null`
- If the user is creating a TEXT index, they can set `tokenize` as desired or `null` for the default tokenizer.

**Comment by rhyshort** [comment]
I've got a couple of other options that take away the need to pass `null` into ensured index for `indexName` and `tokenize`.

```java
        // a builder like pattern
        ds.query().indexer().ensureIndex().named().fields().tokenize().isIndexed();
        
        IndexDefintion def = IndexDefiniton.json().fields().name("index1");
        def = IndexDefiniton.text().fields().name("index1").tokenize("example");
        Index created = ds.query().ensureIndexed(def);  // throws QueryException
```

Using `IndexDefinition` constructor(s) directly would simply shift the problem of `null` appearing 
in the call from `ensureIndexed` to `IndexDefinition`.   Another solution would be to have `Index` double for the definition and the representation of stored index.

I think switching to a builder pattern is the best way to go, it makes it clearer what the method is
doing at the call site, and a user mataining the code doesn't need to wonder "What are those `null`s for".

**Comment by ricellis** [comment]
I think the builder pattern as shown is pretty confusing because it isn't immediately clear what each of these three methods are for:
`.indexer().ensureIndex().isIndexed()`

How would you envisage updating an index with the builder pattern? I think using the whole chained sequence again would be cumbersome, but holding onto an `IndexBuilder` or whatever could be confusing, especially as `isIndexed()` sounds like a `boolean`.

Based on that I'm leaning towards `query().ensureIndexed(def)` but I could be persuaded by a builder with some elaboration on those points.

**Comment by rhyshort** [comment]
`isIndexed()` would trigger the indexing operation on the database. `indexer()` would get the "index builder" with `ensureIndex()` being a link so the code would read better. The names are far from perfect and definitely need more thought if we want a straight builder pattern.

I don't really envision the update indexes to be in the builder pattern. It does mean the API is a bit odd when considered that the other methods are. 

I think I should also clear up that I was thinking more the `IndexDefinition.json()...` as the builder pattern I was thinking we should follow, but I'm still torn on if it should be a new class or simply tacked on to the existing `Index`.

**Comment by tomblench** [comment]
Finally all done now that #471 has merged. Closing.
