### ISSUE TITLE
Simplify `pickWinnerOfConflicts` code

### ISSUE THREAD

**Issue by tomblench** [cloudant/sync-android#332]
See also #326 and #329 - this code has proven to be a bit fragile and can result in no new winner being selected.

A simpler method should be employed:
- Mark all leafs non-current
- Select winning leaf and mark that as current.

Note that these two steps should happen in a transaction so that they appear to be atomic.

The current implementation suffers from micro-optimisation. The slight performance penalty of this proposed solution is out-weighed by the simplicity of the solution.

**Comment by ricellis** [comment]
Merged in #334
