### ISSUE TITLE
Add Schema constraint to to revs table for docid rev id pair.

### ISSUE THREAD

**Issue by rhyshort** [cloudant/sync-android#333]
Add constraint to schema for revs table which restricts docID and revID pair to be unique. This will prevent insertion of duplicate revisions into the revs table. 

To do this migration in the SQLite, the revs table will need to be dropped and recreated. There is previously a migration to one of the other tables. The general sequence is

1. Rename Current table
2. Create a new table with constraint
3. Drop temp table.

**Comment by ricellis** [comment]
We should probably also constrain the attachments table to unique sequence+filename.

**Comment by rhyshort** [comment]
Merged as part of #338
