### ISSUE TITLE
sync-android is complaining that the database is locked

### ISSUE THREAD

**Issue by eforth** [cloudant/sync-android#341]
All queries to the database are sequentially done. I used a `Executors.newSingleThreadExecutor()` to ensure only one task is executed at any time however after successfully executing one task and then moving on to the next I received the following message:

`E/SQLiteLog: (5) database is locked`  and
`E/SQLiteDatabase: Failed to open database /data/data/app/app_datastores/database/extensions/com.cloudant.sync.query/indexes.sqlite`

Below is an example of one of the queries:

`    Datastore ds = DataManager.getInstance().getPersistenceService().getDs();
    ConfigService configService = DataManager.getInstance().getConfigService();
    IndexManager im = new IndexManager(ds);
    DocumentRevision documentRevision = new DocumentRevision();

    Map<String, Object> query = new HashMap<>();
    query.put("patientId", configService.getProfileId());
    query.put("type", "testResults");
    query.put("typeOfTest", "blood_pressure");

    List<Map<String, String>> sortDocument = new ArrayList<>();
    Map<String, String> sortByPatient = new HashMap<>();
    Map<String, String> sortByType = new HashMap<>();
    Map<String, String> sortByTestType = new HashMap<>();
    Map<String, String> sortByTime = new HashMap<>();
    sortByPatient.put("patientId", "desc");
    sortByType.put("type", "desc");
    sortByTestType.put("typeOfTest", "desc");
    sortByTime.put("timeRecorded", "desc");
    sortDocument.add(sortByPatient);
    sortDocument.add(sortByType);
    sortDocument.add(sortByTestType);
    sortDocument.add(sortByTime);

    QueryResult bloodPressureResult = im.find(query, 0, 1, null, sortDocument);

    if (result != null) {
        for (DocumentRevision rev : bloodPressureResult) {
            documentRevision = rev;
        }
    }

    im.close();

    return documentRevision;`

**Can you give me a clue as to why after executing this query (Successfully) and then trying execute something similar that the database would complain that it is locked?**

**Comment by tomblench** [comment]
Hi @eforth we'll try to reproduce your issue and let you know how we get on. The `IndexManager` class actually uses a queue internally for all database access so these should be serialised as long as you always use the same `IndexManager`.

Can you tell us which version of the library you are using?

I would advise you to try using the same `IndexManager` instance throughout the lifetime of your application rather than creating a new one each time. This may help with your issue.

**Comment by eforth** [comment]
I was using version 1.0.0 then upgraded to 1.1.0 but the issue persists. I try out your suggestion.

**Comment by eforth** [comment]
Your suggestion worked. Thanks!

**Comment by rhyshort** [comment]
Great glad it works for you :)
