### ISSUE TITLE
Accuracy of Floating point comparisons in Query.

### ISSUE THREAD

**Issue by rhyshort** [cloudant/sync-android#389]
Query can match on unindexed documents, using the UnindexedMatcher. This matcher compares `double` for all number types. Although this triggers a warning in findbugs, this could be a much bigger problem for example: `compareEq(new Double(1.01), new Float(1.01))` returns `false` when it should be `true`. 

There needs to be a full investigation into the number types used for query. From the SQL matching (and what is returned from SQL) to the java UnindexedMatcher. 

For now as part of #388 the warning will be disabled where required and it should be removed as part of this work if it is possible to do so.

**Comment by tomblench** [comment]
QueryValidator.java explicitly prohibits the use of a float in queries:
```java
    private static boolean validateNotAFloat(Object value) {
        boolean valid = true;

        if (value instanceof Float) {
            valid = false;
            logger.log(Level.SEVERE, "Float value found in query: %f - Use Double instead.", value);
        }

        return valid;
    }
```

**Comment by tomblench** [comment]
As stated `QueryValidator.java` prohibits use of float and we now have regression tests in place to codify this expectation, as done in #447
