### ISSUE TITLE
Update codeStyleSettings.xml so that licence boilerplate is included in new files

### ISSUE THREAD

**Issue by tomblench** [cloudant/sync-android#391]
Also consider using a maven plugin or other appropriate tool to enforce all files having licences.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/sync-android/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
