### ISSUE TITLE
ReplicatorBuilder should take the full `DocumentStore` object.

### ISSUE THREAD

**Issue by rhyshort** [cloudant/sync-android#395]
Currently the `ReplicatorBuilder` takes only the `Database` object from the `DocumentStore` like:

```
mPullReplicator = ReplicatorBuilder.pull().to(mDocumentStore.database).from(uri).build();
 mPushReplicator = ReplicatorBuilder.push().from(mDocumentStore.database).to(uri).build();
```

Which looks a bit off, it would be more natural to take the entire `DocumentStore` object.

**Comment by tomblench** [comment]
Done in #412
