### ISSUE TITLE
Investigate Prohibited fields allowed.

### ISSUE THREAD

**Issue by rhyshort** [cloudant/sync-android#396]
PR #393 removes probibited fields list from `DocumentRevisionBuilder` because it isn't used. This might be indicative of less restrictive. There are also other places which make references to these fields as constants, see `DatastoreConstants.KNOWN_SPECIAL_KEYS` and `CouchConstants`. These probably need to be combined into one set of fields and it needs to verified that we don't allow setting of prohibited keys.

**Comment by tomblench** [comment]
After investigation, this is not an issue. All top-level fields starting with underscore are prohibited. See `createDocument_specialField_fail` test.
