### ISSUE TITLE
Should Misc.getSha1 throw an exception instead of returning an empty byte array?

### ISSUE THREAD

**Issue by rhyshort** [cloudant/sync-android#397]
Currently `Misc. getSha1` returns `null` when it could not calculate the sha1 for a stream, however findbugs regards this as a problem as a result it has been replaced with an empty byte array in pr #393. Some more thought should be put in to wether or not it should throw an exception and if so what exception should be thrown.

**Comment by tomblench** [comment]
Done in #414
