### ISSUE TITLE
v2.0 API discussion points

### ISSUE THREAD

**Issue by tomblench** [cloudant/sync-android#413]
Issue to track discussion points where we don't yet have a clear answer.

We should strike these off and/or open separate issues as and when we resolve what the next steps are for each.

* ~~should DocumentStore query/database be methods instead of fields~~
  we have resolved that the will be methods - this has been merged
* ~~naming proposal for Database methods (create, delete) instead of createDocumentFromRevision~~
  we have agreed on a set of names which are based on CRUD - this has been merged
* ~~`Database` is in documentstore package, but `Query` isn’t but they are peers~~
  we have decided to keep this as-is
* ~~double check API classes and decide if anything should not be public~~
  done, see https://github.com/cloudant/sync-android/issues/413#issuecomment-275451057
* ~~argument checks currently mostly throw `IllegalArgumentException` except `checkNotNull` which throws a `NullPointerException` should we always throw an `IllegalArgumentException`? Perhaps we should consider a checked `Exception` type?~~
  done, see https://github.com/cloudant/sync-android/issues/413#issuecomment-275680032

**Comment by rhyshort** [comment]
With my arbitrary comparison 

```java
documentStore.database.create(revision);
documentStore.query.find(selector);

documentStore.database().create(revision);
documentStore.query().find(selector);
```

And after seeing our Mocks removed in #412, I think having `database` and `query` as methods (without the get prefix) is a nice compromise and allows us to do mocking without doing potential unsafe things to final fields via reflection. 

So my vote is for `.database()` and `.query()`.

**Comment by ricellis** [comment]
Should discuss whether these should be public:

- [ ] `com.cloudant.sync.documentstore.DocumentBodyFactory#EMPTY` -> should be `DocumentBody` not `DocumentBodyImpl`
- [ ] `com.cloudant.sync.documentstore.Changes#Changes` (marked API private), but is in the public package
- [ ] `com.cloudant.sync.documentstore.Changes#getResults` returns a list of `InternalDocumentRevision`
- [ ] Naming of Id vs ID in many places
- [ ] `com.cloudant.sync.documentstore.DocumentRevision#isCurrent` - I think this is probably needed, but might be worth a conversation.
- [ ] `com.cloudant.sync.documentstore.encryption` package I think only `KeyProvider` and `SimpleKeyProvider` need be public?
- [ ] `com.cloudant.sync.query.IndexType#enumValue` is this needed for case insensitivity? All `enum` types have a `valueOf(String name)` method built-in.
- [ ] `com.cloudant.sync.replication.IntervalTimerReplicationPolicyManager` should this move into JavaSE as it says it is not suitable for use on Android?
- [ ] `com.cloudant.sync.replication.ReplicatorBuilder#withId` if this is only needed internally by replication policies it should probably not be exposed on the public builder.

**Comment by ricellis** [comment]
Added branch to change the NPE to `IllegalArgumentException` https://github.com/cloudant/sync-android/tree/413-npe-iae

**Comment by ricellis** [comment]
Other changes in branch https://github.com/cloudant/sync-android/tree/413-api-cleanup

**Comment by brynh** [comment]
I think I agree with most of the points except that `com.cloudant.sync.replication.ReplicatorBuilder#withId` is used in the setup of a replication policy by a user, so I think we need to keep it in the public builder. Its use is described in the [replication policies guide](https://github.com/cloudant/sync-android/blob/master/doc/replication-policies.md#service)

**Comment by ricellis** [comment]
@brynh thanks for the feedback. Regarding `ReplicatorBuilder.withId()` after further consideration I think it makes sense to leave it in place, since the alternative (for example passing the `Replicator` instance itself into the listener) requires exposing the `Replicator` which is much harder to do statically, and that makes the comparisons more difficult.

When looking at it however, I did notice a couple of other API issues in the replication policies:
- [ ] The `ReplicationPolicyManager.ReplicationListener` is public, but only because the `EventBus` needs access to it. I think it should move into the `internal` package.
- [ ] There are two nearly identical interfaces `ReplicationPolicyManager.ReplicationsCompletedListener` and `ReplicationService.ReplicationCompleteListener` - I think the latter could be deleted and just use the former interface.

wdyt?

**Comment by brynh** [comment]
@ricellis Yes, I agree that your suggestions make sense. Maybe as well to move `SimpleReplicationCompleteListener` to `ReplicationPolicyManager` as well.
