### ISSUE TITLE
v2 API: Static FTS code crashes on some devices

### ISSUE THREAD

**Issue by brynh** [cloudant/sync-android#449]
The method `isFtsAvailable()` in `SQLDatabaseFactory` crashes during the call to `endTransaction()` on certain devices. The crash ultimately occurs in the call to `nativeExecute(...)` in the `execute(...)` method in `SQLiteConnection.java`.

This appears to be a device specific issue rather than a bug in sync-android. It has currently only been observed on:
* Motorola Moto G 2nd Gen (XT1068) running Android 6.0 (Marshmallow).

The output from `adb logcat` when testing with the `todo-sync` example app shows:
```console
12-16 15:08:31.272 F/libc    (25724): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 25724 (m.cloudant.todo)
12-16 15:08:31.374 F/DEBUG   ( 4024): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-16 15:08:31.374 F/DEBUG   ( 4024): Build fingerprint: 'motorola/titan_retgb/titan_umtsds:6.0/MPB24.65-34/31:user/release-keys'
12-16 15:08:31.374 F/DEBUG   ( 4024): Revision: 'p400'
12-16 15:08:31.374 F/DEBUG   ( 4024): ABI: 'arm'
12-16 15:08:31.374 F/DEBUG   ( 4024): pid: 25724, tid: 25724, name: m.cloudant.todo  >>> com.cloudant.todo <<<
12-16 15:08:31.374 F/DEBUG   ( 4024): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
12-16 15:08:31.399 F/DEBUG   ( 4024):     r0 b8c69398  r1 be811410  r2 00000000  r3 b8c92d20
12-16 15:08:31.400 F/DEBUG   ( 4024):     r4 b8c691f0  r5 b6897118  r6 00000000  r7 b8c68828
12-16 15:08:31.400 F/DEBUG   ( 4024):     r8 00000001  r9 b8c691f0  sl 00000000  fp 00000002
12-16 15:08:31.400 F/DEBUG   ( 4024):     ip b6e90ea0  sp be8113e8  lr b67eae5b  pc 00000000  cpsr 200f0010
12-16 15:08:31.404 F/DEBUG   ( 4024):
12-16 15:08:31.404 F/DEBUG   ( 4024): backtrace:
12-16 15:08:31.405 F/DEBUG   ( 4024):     #00 pc 00000000  <unknown>
12-16 15:08:31.405 F/DEBUG   ( 4024):     #01 pc 00024e59  /system/lib/libsqlite.so
12-16 15:08:31.405 F/DEBUG   ( 4024):     #02 pc 00024173  /system/lib/libsqlite.so
12-16 15:08:31.406 F/DEBUG   ( 4024):     #03 pc 0000e759  /system/lib/libsqlite.so
12-16 15:08:31.406 F/DEBUG   ( 4024):     #04 pc 0002be41  /system/lib/libsqlite.so
12-16 15:08:31.406 F/DEBUG   ( 4024):     #05 pc 00039ad7  /system/lib/libsqlite.so
12-16 15:08:31.406 F/DEBUG   ( 4024):     #06 pc 0000ffc5  /system/lib/libsqlite.so (sqlite3_step+724)
12-16 15:08:31.406 F/DEBUG   ( 4024):     #07 pc 00075071  /system/lib/libandroid_runtime.so
12-16 15:08:31.406 F/DEBUG   ( 4024):     #08 pc 71e6b8bb  /data/dalvik-cache/arm/system@framework@boot.oat (offset 0x1fd1000)
12-16 15:08:31.779 W/ActivityManager( 1825):   Force finishing activity com.cloudant.todo/.TodoActivity
12-16 15:08:31.779 F/DEBUG   ( 4024):
12-16 15:08:31.779 F/DEBUG   ( 4024): Tombstone written to: /data/tombstones/tombstone_00
12-16 15:08:31.779 E/DEBUG   ( 4024): AM write failed: Broken pipe
12-16 15:08:31.780 I/ActivityManager( 1825): moveHomeStack, setupComplete:true
12-16 15:08:31.780 I/BootReceiver( 1825): Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
12-16 15:08:31.810 I/Zygote  (  437): Process 25724 exited due to signal (11)
```

# Workaround 
Investigation has shown that if the transaction is marked as successful, the crash does not occur.  This means we could potentially work around this issue by marking the transaction as successful and also adding a `DROP TABLE` statement to remove the table used for the check, thus having a similar effect to rolling back the transaction. For example, the following has been tested and successfully works around the issue - changing the call to `execSQL()` in `isFtsAvailable()` to also drop the table:
```java
tempInMemoryDB.execSQL(
   String.format("CREATE VIRTUAL TABLE %1$s USING FTS4 ( col ); DROP TABLE %1$s;",
      FTS_CHECK_TABLE_NAME));
```
and marking the transaction as successful immediately before the call to `endTransaction()`:
```java
tempInMemoryDB.setTransactionSuccessful();
```

**Comment by ricellis** [comment]
@brynh Given the nature of the native and workaround sounds like it could be a SQLite bug. It could be interesting to know what version is included on that device, which I think is normally output in the log somewhere.

**Comment by brynh** [comment]
The version of SQLite on the Motorola XT1068 on which the bug was observed is 3.8.10.2

**Comment by brynh** [comment]
Further testing on the following devices:
* Sony Xperia Z3 (D6603) running Android 6.0.1;
* Google (ASUS) Nexus 7 (2013) running Android 6.0.1

shows both these also use SQLite 3.8.10.2 but do not crash in the way the Motorola XT1068 does.

**Comment by ricellis** [comment]
Interesting, but sadly doesn't really help us get to the bottom of it! Let's proceed with the workaround.
