### ISSUE TITLE
Connection refused when replicating on push notification receive

### ISSUE THREAD

**Issue by falmanna** [cloudant/sync-android#488]
Hello,

I have encountered a strange error when trying to do pull replication on receiving a push notification from GCM.

I am using a Replication Service to do the replication. What makes this error strange is that the replication process works as expected whenever the phone is awake, either by using the application or when connecting the phone to usb. It only happens when the phone is sleep and a notification is received. And I was able to get the log by writing it to a file.

This exception is only happening on some devices, most of them have custom ROMs.
I think that this problem is happening because the phone is blocking all network connection when in a sleep state. Although I acquired `wakelock` and `wifilock` before starting the replication, but I still receive this error.

I am still not sure if this problem is related to Cloudant library or not. I just thought it is good to report it,
Attached the log file.

[error.txt](https://github.com/cloudant/sync-android/files/721884/error.txt)

**Comment by brynh** [comment]
@firasalmanna: Thank you for reporting this. Can you confirm whether you are using [Replication Policies](https://github.com/cloudant/sync-android/blob/master/doc/replication-policies.md#android-replication-policies) and a subclass of [ReplicationService](https://github.com/cloudant/sync-android/blob/master/cloudant-sync-datastore-android/src/main/java/com/cloudant/sync/replication/ReplicationService.java) or your own `Service` based solution for replication?

I assume in the log you've sent where it says `failed to connect to user.cloudant.com/ip (port 443)`, you have modified that to hide your username and it's not really the address you are connecting to.

It is interesting that this seems to be mainly happening on devices with custom ROMs, which could be doing something non-standard to block the connections, which would then be difficult to fix.

Can you also tell us what version of the Cloudant sync-android library you are using?

**Comment by firasalmanna** [comment]
@brynh: Yes I am using `Replication Polices` and a service that extends `ReplicationService.java`.    
and Yes I modified my username account to `user`.

The phones that are repeatedly sending the error are Lenovo, Huawei, Xiaomi, and few others.
I am using `latest.release`, so it should be the latest version

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/sync-android/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
