### ISSUE TITLE
Allow setting of custom HTTP headers for replications

### ISSUE THREAD

**Issue by alfinkel** [cloudant/sync-android#51]
After some investigation I believe that we should be able to follow a similar paradigm as is done in CDTDatastore and detailed in [Task 36445][Task 36445] to implement the setting of custom headers for replications in sync-android.

Specifically:

- Update the abstract class [Replication.java][Replication.java] by adding an optionalHeaders map as a property and adding a method that gets/checks the contents of the map similar to dictionaryForReplicatorDocument: in [CDTAbstractReplication][CDTAbstractReplication].
- Update [HttpRequests.java][HttpRequests.java] by adding a requestHeaders map property and all necessary code to manage requestHeaders and set the the new headers on each request accordingly.
- Minor updates to [BasicPullStrategy.java][BasicPullStrategy.java], [BasicPushStrategy.java][BasicPushStrategy.java], [CouchClientWrapper.java][CouchClientWrapper.java], and [CouchClient.java][CouchClient.java] to accommodate the new change and make the optionalHeaders map available to HttpRequests.
- These proposed changes should have no impact on any other set of functionality outside of replication.

@mikerhodes, @tomblench, @gadamc let me know if this makes sense.  I can add greater detail as well if necessary.

[Task 36445]: https://cloudant.fogbugz.com/f/cases/36445/Expose-TDReplicator-requestHeaders-to-CDTPull-PushReplication-configuration-objects

[Replication.java]: https://github.com/cloudant/sync-android/blob/master/sync-core/src/main/java/com/cloudant/sync/replication/Replication.java

[CDTAbstractReplication]: https://github.com/cloudant/CDTDatastore/blob/master/Classes/common/CDTReplicator/CDTAbstractReplication.m

[HttpRequests.java]: https://github.com/cloudant/sync-android/blob/master/sync-core/src/main/java/com/cloudant/mazha/HttpRequests.java

[BasicPullStrategy.java]: https://github.com/cloudant/sync-android/blob/master/sync-core/src/main/java/com/cloudant/sync/replication/BasicPullStrategy.java

[BasicPushStrategy.java]: https://github.com/cloudant/sync-android/blob/master/sync-core/src/main/java/com/cloudant/sync/replication/BasicPushStrategy.java

[CouchClientWrapper.java]: https://github.com/cloudant/sync-android/blob/master/sync-core/src/main/java/com/cloudant/sync/replication/CouchClientWrapper.java

[CouchClient.java]: https://github.com/cloudant/sync-android/blob/master/sync-core/src/main/java/com/cloudant/mazha/CouchClient.java

**Comment by tomblench** [comment]
Fixed PR #78
