### ISSUE TITLE
Additional tests for queries combining $not and $size

### ISSUE THREAD

**Issue by emlaver** [cloudant/sync-android#519]
The original issue #468 contains discussion about [adding tests](https://github.com/cloudant/sync-android/issues/468#issuecomment-286405751) that are similar to the tests in CDT PR [354](https://github.com/cloudant/CDTDatastore/pull/354).

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/sync-android/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
