### ISSUE TITLE
Package com.cloudant.sync.datastore.encryption should be renamed

### ISSUE THREAD

**Issue by brynh** [cloudant/sync-android#523]
Since the changes migrating from `datastore` to `documentstore` in the v2 API, for consistency, the package [`com.cloudant.sync.datastore.encryption`](https://github.com/cloudant/sync-android/tree/f0bfc711f3f31669faedf2f9bf98c739d46ce6bc/cloudant-sync-datastore-android-encryption/src/main/java/com/cloudant/sync/datastore/encryption) should probably now be `com.cloudant.sync.documentstore.encryption`.

The tests should also be moved:
> ./cloudant-sync-datastore-android-encryption/src/test/java/com/cloudant/sync/datastore
./cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/datastore/encryption

**Comment by ricellis** [comment]
Shame this was missed for 2.x, but I think it would be API breaking to rename it now, so sadly it will probably have to wait until 3.x.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/sync-android/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
