### ISSUE TITLE
Failed to resolve: com.google.android:android:4.0.1.2

### ISSUE THREAD

**Issue by Appelonius** [cloudant/sync-android#530]
Hi,

Not sure if this is a lib issue or something else but I'm using the new Android Studio 3.0 build with gradle 3.0.0-alpha1 build tools.
It seems the new gradle does not want to compile the cloudant-sync-datastore-android module anymore.
It fails with the following error 'Failed to resolve: com.google.android:android:4.0.1.2'
I checked the module build.gradle and verified it is still in the dependency list.
Is this still necessary?

Any clue on how to fix it?

Best regards,
A.

**Comment by tomblench** [comment]
We haven't tried Android Studio 3.0 but it looks like the build system has changed a lot. We'll investigate and get back to you.

**Comment by defaultbr** [comment]
i think this became more critical, now Android Studio FORCE you to update gradle:

![screenshot from 2017-06-11 15-50-39](https://user-images.githubusercontent.com/5432351/27013725-fb87d014-4ebf-11e7-927f-60bd4308f59d.png)


(the variable think doesnt worked) and when i update it to latest, this error that op has reported pop up

![screenshot from 2017-06-11 15-54-33](https://user-images.githubusercontent.com/5432351/27013727-123f4aa8-4ec0-11e7-8f83-dfc5eb0ed4fe.png)

**Comment by tomblench** [comment]
@Appelonius @defaultbr sorry this took us a while but the issue should be fixed in the latest snapshot build. Note that Android Studio 3.0 and related build tools are still in alpha stage and liable to change in the future.

You can use snapshot builds of our library by making the following changes to your build.gradle:

```groovy
repositories {
    mavenLocal()
    // enable this to build from latest snapshot release
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    mavenCentral()
}
```
and
```groovy
dependencies {
    // use 'latest.integration' to build from latest snapshot release
    compile(group: 'com.cloudant', name: 'cloudant-sync-datastore-android', version:'latest.integration')
}
```

In our testing this version should work with Android Studio 3.0 Canary 3 but we would be grateful if you can confirm this fix works for you before we make an official release with this fix.

**Comment by defaultbr** [comment]
Hello @tomblench, it solved for me, thank you so much!!

**Comment by Appelonius** [comment]
Hi @tomblench,

Sorry for the late response!
Same here. The build is working now.
Thanks for the quick response and fix!

Best regards,
A.

**Comment by tomblench** [comment]
Great news. We have now released a version with this fix, see https://github.com/cloudant/sync-android/releases/tag/2.0.2
