### ISSUE TITLE
We should build the Android library using the modern build process

### ISSUE THREAD

**Issue by tomblench** [cloudant/sync-android#531]
`cloudant-sync-datastore-android` sub-project should be built as an AAR as per https://developer.android.com/studio/projects/android-library.html.

See also #530, https://android-developers.googleblog.com/2017/05/android-studio-3-0-canary1.html

**Comment by ricellis** [comment]
We also need to update the android dependencies we need to be `aar`s - so that the modern Android build tooling can handle them correctly. See e.g. #603 and https://github.com/cloudant/sync-android/blob/96ae3b145bf7db8b49fb98cbfd7fc41fbbd5a3a9/cloudant-sync-datastore-android/build.gradle#L4

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/sync-android/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
