### ISSUE TITLE
how to know if a Revision was at least pushed to server?

### ISSUE THREAD

**Issue by defaultbr** [cloudant/sync-android#538]
Is there any way to know if a revision was pushed to server?

i think i can build a system to listen for each push and save the id and than create a list where i can check, but is there any built in way of knowing it?

**Comment by smithsz** [comment]
You can use the `_revs_diff` endpoint (see [docs](https://console.bluemix.net/docs/services/Cloudant/api/advanced.html#-post-database-_revs_diff-)) to check the revisions available on the server.

The library doesn't support checking the status of individual revisions. Although, once a push replication has completed without error you can be sure all new revisions have been uploaded to the server.

If you can give us some more details regarding your use case than perhaps there's a better solution to your problem.

**Comment by defaultbr** [comment]
@smithsz Hello, thanks the answer!!

my clients can create n numbers of a specific doc_type revision and i show them the information about quantity of this revision need to upload,  if its uploaded correctly i cant simple edit the file to set "upload = true" , if i do this, next update cycle it will consider the revision updated and try to send it again


the PushFilter is working properly? maybe i can filter document where upload != true

**Comment by defaultbr** [comment]
@tomblench  thanks the answer, i got but i can i see where it will fail:

20:08:01

Created doc1 -> sequence 1
Created doc2 -> sequence 2
database().lastSequence -> 2

Before push

**Comment by tomblench** [comment]
@defaultbr have you tried this approach yet? I saw some comments via email but not on here. To clarify the steps would look like:

- Create database
- Set `lastPushedSequence=0` and record this somewhere
- Create doc1
- Create doc2
- Invoking `changes` with `lastPushedSequence` would now show doc1, doc2
- Perform push replication
- Set `lastPushedSequence=getLastSequence()` (2) and record this somewhere
- Create doc3
- Invoking `changes with `lastPushedSequence` would now show doc3
... etc

**Comment by defaultbr** [comment]
Hello @tomblench , thanks the steps, i will test and post here ok? thank you so much for the idea =)
