### ISSUE TITLE
Query equality not working for numbers in String

### ISSUE THREAD

**Issue by defaultbr** [cloudant/sync-android#541]
all this queries (without quotation because .toString() removed it)

```
String code = "0008" or String code = "8"


EmployeeSEARCHQUERY: {enabled=true, code={$eq=0008}, doc_type=Employee}
EmployeeSEARCHQUERY: {enabled=true, code={$eq=8}, doc_type=Employee}
EmployeeSEARCHQUERY: {enabled=true, code=0008, doc_type=Employee}
EmployeeSEARCHQUERY: {enabled=true, code=8, doc_type=Employee}
```

return the same RESULT:

Document
```
{"companies":["575eb6d3a098db6820979303"],"code":"0008","oid":"575ebc32a098db6820979313","allowFeedback":false,"name":"Aninha","doc_type":"Employee"}
```

its something wrong with the query?

expected to return the Document only for this cases:

```
EmployeeSEARCHQUERY: {enabled=true, code={$eq=0008}, doc_type=Employee}

or

EmployeeSEARCHQUERY: {enabled=true, code=0008, doc_type=Employee}
```

and not for the others without 000 (remember, its a string and there is not reason to remove the 000 in the begining

**Comment by emlaver** [comment]
Hi @defaultbr, can you please share the code you're using to run these queries?

**Comment by defaultbr** [comment]
@emlaver  of course:


```
 fun getEmployeeByCode(password: String, enabled: Boolean): Employee? {
        var employee: Employee? = null
        val query = HashMap<String, Any>()
        query.put("doc_type", "Employee")
        query.put("code", password)
        query.put("enabled", enabled)
        var result: QueryResult? = null
        try {
            result = cQuery.find(query)
            if (result != null) {
                for (revision in result) {
                    if (!revision.isDeleted) {
                        employee = GsonUtils.getGson().fromJson(revision.body.toString(), Employee::class.java)
                    }
                }
            }
        } catch (e: QueryException) {
            e.printStackTrace()
        }
        return employee
    }
``` 

obs: i have a missing break; inside the if(!revision.isDeleted), but no problem, i can add later

**Comment by emlaver** [comment]
@defaultbr Thanks for sharing the code.  I'm able to see your expected results of just two of the four cases.  Here is a gist of the code in Java to save your document and run the queries: https://gist.github.com/emlaver/a6dc360ebc1d29cf1d4807917c412cd5.  

[This line](https://gist.github.com/emlaver/a6dc360ebc1d29cf1d4807917c412cd5#file-querytest-java-L47) is where I build the first query case.  You'll see that I created a new `query` map for each case, then I pass that query to `getEmployeeByCode` method.  I've modified your `getEmployeeByCode` to allow for `Map` to be passed in and for a `DocumentStore` object that's used to call `find`.
Note: I ran these queries without the `enabled=true` option as I didn't add an index.  

Output from code:
```
Query result for $eq: "0008": {"companies":["575eb6d3a098db6820979303"],"code":"0008","oid":"575ebc32a098db6820979313","allowFeedback":false,"name":"Aninha","doc_type":"Employee"}
Query result for $eq: "8": null
Query result for "0008": {"companies":["575eb6d3a098db6820979303"],"code":"0008","oid":"575ebc32a098db6820979313","allowFeedback":false,"name":"Aninha","doc_type":"Employee"}
Query result for "8": null
```

**Comment by defaultbr** [comment]
@emlaver thanks effort  =)!

but im i little lost where your code is diff from mine that made your code to work correctly

**Comment by emlaver** [comment]
@defaultbr One part that is different:
When you build the `query` hashmap, you pass the `password` as a string.  You'll need to use a `Map` object when creating the queries with the `$eq` operator: https://gist.github.com/emlaver/a6dc360ebc1d29cf1d4807917c412cd5#file-querytest-java-L49.

**Comment by emlaver** [comment]
@defaultbr I also noted that I removed the `enabled=true` option.  Are you able to run my example code against your query index and verify it works as expected?

**Comment by defaultbr** [comment]
no success, even changing to map(mutableMap in kotlin) or creating a java class to handle it:

```
public static void getEmployeeMap(String code, boolean enabled, DocumentStore ds) {
        Map<String, Object> query = new HashMap<String, Object>();
        query.put("doc_type", "Employee");
        Map<String, Object> eq = new HashMap<String, Object>();
        eq.put("$eq", code);
        query.put("code", eq);
        query.put("enabled", enabled);
        QueryResult result = null;
        try {
            result = ds.query().find(query);
            if (result != null) {
                for (DocumentRevision revision :result) {
                    if (!revision.isDeleted()) {
                        System.out.println(("NEW QUERYRESULT: " + revision.getBody().toString()));
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
}
```

and the queries + result:


Query 1 -> 
```
NEW QUERY: {doc_type=Employee, code={$eq=1}, enabled=true}

NEW QUERYRESULT: {"companies":[],"allowFeedback":false,"name":"Testing","doc_type":"Employee", "code":"1"}
```


Query 2 -> 
```
NEW QUERY: {doc_type=Employee, code={$eq=01}, enabled=true}

NEW QUERYRESULT: {"companies":[],"allowFeedback":false,"name":"Testing","doc_type":"Employee", "code":"1"}
```

and im using Map now (**Map<String, Object> query**...)

**Comment by emlaver** [comment]
@defaultbr Can you comment out the `query.put("enabled", enabled)` line, run the code and share your results? Also, can you share your Cloudant query index?

**Comment by defaultbr** [comment]
@emlaver 

Query Indexes
```
            println("CREATE/REFRESH INDEXXES")
            val query_by_oid = ds.query().createJsonIndex(Arrays.asList(FieldSort("oid")), "query_by_oid")
            val query_by_doc_type = ds.query().createJsonIndex(Arrays.asList(FieldSort("doc_type")), "doc_type")
            val query_device = ds.query().createJsonIndex(Arrays.asList(FieldSort("imei"), FieldSort("doc_type")), "device1")
            **val query_employee_doctype_enabled_code = ds.query().createJsonIndex(Arrays.asList(FieldSort("enabled"), FieldSort("code"), FieldSort("doc_type")), "query_employee1")**
            val query_employee_oid_doctype = ds.query().createJsonIndex(Arrays.asList(FieldSort("oid"), FieldSort("doc_type")), "query_employee2")
```

**Comment by defaultbr** [comment]
"Close and Comment" is like a "Press here to destroy the world", its a button impossible to not click :1st_place_medal:

**Comment by emlaver** [comment]
@defaultbr I added your index and ran my code. I now see the results you get where all 4 cases show in my output.  This means there's an issue with your `query_employee_doctype_enabled_code` query index.  I will check to see what needs to be changed in your index.

**Comment by defaultbr** [comment]
@emlaver  okkk, thanks =)

**Comment by tomblench** [comment]
@defaultbr unfortunately this is due to he way that the underlying SQLite database index tables are defined. The string "0008" is being coerced to the number "8" when it is being stored by SQLite. Some of these details can be found [here](https://www.sqlite.org/datatype3.html#type_affinity).

Unfortunately there isn't a quick fix for this as it affects a large part of the code base and may break compatibility with existing versions.

**Comment by defaultbr** [comment]
Hello @tomblench  i understand!!

maybe i need to add a prefix, so it will stop to guess string to number


thank you =)
