### ISSUE TITLE
Replicator/ReplicatorBuilder ignores URI credentials 

### ISSUE THREAD

**Issue by RHV044** [cloudant/sync-android#545]
Hello, I'm using Cloudant-sync android latest release so far: 2.0.2 and targeting Android api 21+
My server database is CouchDB 2.1.0

I'm trying to trigger a replication pull from my android app, to update the local db.
I'm giving the source URI to the ReplicatorBuilder like: "https://user:password@databaseurl/db_name"
(as specificated here https://github.com/cloudant/sync-android/blob/master/doc/replication.md)
but in the generated replicator object, if I inspect "replicator.strategy.sourceDb" the db uri is just "https://databaseurl/db_name" and so, i get unhautorized (it works fine if I deactivate the security check on the database server)

This is my running code:
```
public ReplicationListener pullAllAsync(Databases db_name) {
        try {
            URI uri = db_name.getServerURI();
            DocumentStore ds = DocumentStore.getInstance(new File(db_name.getMobilePath(), db_name.toString()));
            Replicator replicator = ReplicatorBuilder
                    .pull()
                    .from(uri)
                    .to(ds)
                    .build();
            ReplicationListener listener = new ReplicationListener(replicator);
            replicator.getEventBus().register(listener);
            replicator.start();
            return listener;
        } catch (Exception e) {
            e.printStackTrace();
            LogRepository.getInstance().escribirLog(LogRepository.TipoLog.ERROR, null, e, true);
            return null;
        }
    }
```

Am I doing something wrong?

Thanks!

**Comment by RHV044** [comment]
Well, the problem seems to be with the CookieAuthentication (which is the default authentication method of the Replicator when creds are passed with in the URI) I don't really know why is it failing, because the CouchDB server instance is configured to accept CookieAuthentication.

Anyway, this may not be the best possible solution, but is a good enough workaround. I have made this work by forcing the BasicAuthentication method as follows:
`public ReplicationListener pullAllAsync(Databases db_name) {
    try {
        URI uri = db_name.getServerURI();

        DocumentStore ds = DocumentStore.getInstance(new File(db_name.getMobilePath(), db_name.toString()));
        Replicator replicator = ReplicatorBuilder
                .pull()
                .from(uri)
                .to(ds)

                //WORKAROUND: forces BasicAuthentication method instead of CookieAuthentication
                .addRequestInterceptors(new BasicAuthInterceptor(uri.getRawUserInfo()))
                .build();

        ReplicationListener listener = new ReplicationListener(replicator);
        replicator.getEventBus().register(listener);
        replicator.start();
        return listener;
    } catch (Exception e) {
        e.printStackTrace();
        LogRepository.getInstance().escribirLog(LogRepository.TipoLog.ERROR, null, e, true);
        return null;
    }
}`

**Comment by emlaver** [comment]
Hi @RHV044, could you please share your logs for the code in your first post? 
When you pass in a URI containing the `username:password`, we remove the credentials [here](https://github.com/cloudant/sync-android/blob/1317231e9c7d70fa4032ac04623617c2b454796a/cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/replication/ReplicatorBuilder.java#L78) and use the username and password when creating the cookie interceptor.  The final URI [returned here](https://github.com/cloudant/sync-android/blob/1317231e9c7d70fa4032ac04623617c2b454796a/cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/replication/ReplicatorBuilder.java#L118) will have the credentials removed from the URI which is why you don't see them when you inspect `replicator.strategy.sourceDb`.

**Comment by ricellis** [comment]
@RHV044 Is your CouchDB configured with [`require_valid_user`](http://docs.couchdb.org/en/stable/config/auth.html?highlight=require_valid_user#chttpd/require_valid_user) : `true`?
If that option is enabled the request to `_session` can't be made anonymously. That could possibly explain why using BasicAuth is working, but cookie auth isn't.

**Comment by emlaver** [comment]
Closing as stale. Please re-open if you provide answers to the above questions.
