### ISSUE TITLE
Update CouchDB link for filtered replication in doc

### ISSUE THREAD

**Issue by azri92** [cloudant/sync-android#549]
In the [Replication doc](https://github.com/cloudant/sync-android/blob/master/doc/replication.md#filtered-pull-replication), the CouchDB link doesn't work anymore. 
Here's the latest link:
http://docs.couchdb.org/en/2.1.1/replication/intro.html#controlling-which-documents-to-replicate

**Comment by emlaver** [comment]
Hi @azri92, thanks for reporting this.  We have plans to update deprecated links and I will add this to our list.

**Comment by azri92** [comment]
Cool! Looking forward to the updates 😄
