### ISSUE TITLE
Proguard on Android

### ISSUE THREAD

**Issue by azri92** [cloudant/sync-android#552]
I implemented sync-android on my Android app following the sample todo app. 
My app is written in **Kotlin**. Not sure if this is important but stating it here anyway.
Everything worked fine until I enabled Proguard. Since there was no mention of Proguard in the README or docs, I followed the Proguard config file from the sample app as below:

```
-keepattributes Signature,*Annotation*,EnclosingMethod
-keepattributes InnerClasses
-keepattributes SourceFile,LineNumberTable
-keepnames class com.fasterxml.jackson.** { *; }
-keep class org.w3c.dom.bootstrap.DOMImplementationRegistry
-keep class javax.inject.** { *; }
-keep class com.cloudant.** { *; }
-dontwarn com.cloudant.http.**
-dontwarn com.fasterxml.jackson.**
```

However, I realized that the completion event was not being fired. After much debugging, I figured out that the following methods (from [TaskModel.java](https://github.com/cloudant/sync-android/blob/master/sample/todo-sync/src/com/cloudant/todo/TasksModel.java)) were being removed:
```
    /** javadoc comment */
    @Subscribe
    public void complete(ReplicationCompleted rc) {
        // handler code..
    }

    /** javadoc comment */
    @Subscribe
    public void error(ReplicationErrored re) {
       // handler code..
    }
```

So, I went ahead and set a rule to keep all the public methods etc within my class:
```
-keep class com.azri.myapp.service.DataModel {
  public *;
}
```

And fixed!

My issue now is:

1. Did I miss something else that was obvious that I shouldn't have to set a different proguard rule?
2. If I did the right things, maybe this should be mentioned explicitly in the README or docs? This is usually done for a lot of libraries I've seen.

Thanks! 😄

**Comment by ricellis** [comment]
> Did I miss something else that was obvious that I shouldn't have to set a different proguard rule?

No, I think you did the correct thing. The sample application uses the same `com.cloudant` namespace prefix as the library, so `-keep class com.cloudant.** { *; }` is sufficient for the sample application to work. Your app has a different namespace so an additional `keep` is needed to preserve the `@Subscribe` methods that are reflectively invoked (and therefore not detected by ProGuard).

>If I did the right things, maybe this should be mentioned explicitly in the README or docs? This is usually done for a lot of libraries I've seen.

Yes, I think we could improve the Event docs to make it more obvious that `@Subscribe` methods are invoked reflectively and so will need specific ProGuard excludes.

**Comment by azri92** [comment]
Ah! Figures. Thanks for the info. :D
