### ISSUE TITLE
seq_interval error against Cloudant local

### ISSUE THREAD

**Issue by emlaver** [cloudant/sync-android#557]
Rich tested the `seq_interval` [change](https://github.com/cloudant/sync-android/pull/553) on Cloudant Local and got this message:
```
CouchException: error: unknown_error, reason: badarg, statusCode: 500
```
Welcome string for Cloudant Local:
```
{“couchdb”:“Welcome”,“version”:“1.0.0.5-local”,“vendor”:{“name”:“Cloudant, an IBM Company”,“version”:“1.0.0.5”,“variant”:“local”},“features”:[“geo”]}
```

The [test util method](https://github.com/cloudant/sync-android/blob/master/cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/internal/mazha/ClientTestUtils.java#L242) checks for `version` which CouchDB, Cloudant, and Cloudant local all have.
We may need to consider checking the version under `vendor` JSON object.

Note: In CouchDB 1.x, the seq_interval should be safely ignored.

**Comment by ricellis** [comment]
The `seq_interval` does not cause an error in version 1.1.0 of Cloudant Local. I've updated the test infra to that version, so hopefully we can just close this out if we get some green builds on that.

**Comment by ricellis** [comment]
The tests pass against the newer version, so closing this out.
