### ISSUE TITLE
How to create new database from this library ? 

### ISSUE THREAD

**Issue by ZaheerUdDeen** [cloudant/sync-android#559]
Please include the following information in your ticket.

- I don't see any help to create a new database from this library.
- There is a sample application for CRUD but no database creation help there.
    - If any sample application available for JavaSE please provide that as well. 
    - The JavaSE sample application should contain database creation with CRUD example.
    Thanks.

**Comment by tomblench** [comment]
We have extensive documentation in the [README](https://github.com/cloudant/sync-android/blob/master/README.md), in the [doc](https://github.com/cloudant/sync-android/tree/master/doc) directory and in the [javadoc](https://www.javadoc.io/doc/com.cloudant/cloudant-sync-datastore-core/2.0.2).

You should be able to get started easily enough:
- Create a database on Cloudant with appropriate permissions (eg an API key with read/write permissions).
- Follow the code [here](https://github.com/cloudant/sync-android/blob/master/README.md#overview-of-the-library) to create a local database and populate it with a document. On Java SE you just need to adjust the first line which is Android specific, to point to a location where you want to store your database.
- [Replicate](https://github.com/cloudant/sync-android/blob/master/README.md#replicating-data-between-many-devices) your data by pushing it to Cloudant or pulling it from Cloudant. When replication is complete, your local changes will be reflected remotely or vice versa.

**Comment by ZaheerUdDeen** [comment]
To implement the following 
    https://github.com/cloudant/sync-android/blob/master/doc/CrudSamples.java
CRUD sample in javaSE I am facing the error below. I have tried the to get the answer from different forums like StackOverflow & google etc but failed. 
![image](https://user-images.githubusercontent.com/11150958/33887448-97e3b4be-df6b-11e7-9822-ecdb599f86c3.png)

Kindly Help.
thanks.

**Comment by Appelonius** [comment]
Hi,

It seems you are missing the SQLite4Java libraries. Sync-Android has dependencies on it.
I've had the same issue some time ago. Are you deploying your program on the Raspberry Pi?
If so, you'll need to add this library manually. 

Check this link for more info: 
https://stackoverflow.com/questions/21750601/sqlite4java-on-raspberry-pi

**Comment by ZaheerUdDeen** [comment]
No I am developing the application in JavaSE desktop application with javaFX in eclipse.

**Comment by ZaheerUdDeen** [comment]
Can some have the solution to this problem, please?

**Comment by tomblench** [comment]
You need the native DLL for sqlite4java: https://bitbucket.org/almworks/sqlite4java/wiki/GettingStarted

Depending on where you install that DLL you may need to give your java program the path to this DLL by setting the flag
`-Dsqlite4java.library.path={path}`

Note that we included the native libraries for Linux and MacOS in the `native` sub-directory but none of us test or develop on Windows - sorry about that.

**Comment by ZaheerUdDeen** [comment]
I have tried this: https://bitbucket.org/almworks/sqlite4java/wiki/GettingStarted
I have no idea to set the flag(-Dsqlite4java.library.path={path}) please, any guide to do this?

**Comment by ricellis** [comment]
You need the value of the system property `sqlite4java.library.path` to be the path of the directory where you put the SQLite4Java native files (e.g. `*.dll`) you downloaded for your platform.

**Comment by ZaheerUdDeen** [comment]
I have set System variable path under system property(As below)
![image](https://user-images.githubusercontent.com/11150958/33951234-417a26f4-e050-11e7-9c67-47722855a903.png)

This is the directory where all the native files are available.(As below)
![image](https://user-images.githubusercontent.com/11150958/33951295-6f2c1c88-e050-11e7-8359-f78678b032f1.png)

This is the project build path(As below)
![image](https://user-images.githubusercontent.com/11150958/33951373-99b94b92-e050-11e7-9080-9097a833952e.png)

The same error exists.

**Comment by ricellis** [comment]
You've got the wrong gradle dependency, I can see `cloudant-client-2.11.0.jar` which is java-cloudant but you're trying to use sync-android (project name is android but it works on JavaSE too) here. As per https://github.com/cloudant/sync-android#gradle-or-maven point 3, the dependency is:
```
dependencies {
    compile group: 'com.cloudant', name: 'cloudant-sync-datastore-javase', version:'latest.release'
}
```

**Comment by ZaheerUdDeen** [comment]
I am already using this dependency for android-sync
![image](https://user-images.githubusercontent.com/11150958/33951853-f39575a4-e051-11e7-9729-c773920f11f4.png)

And dependency is already included in "project and external dependency"(As Below)
![image](https://user-images.githubusercontent.com/11150958/33951953-31750218-e052-11e7-93b6-19b39f48014c.png)

**Comment by ZaheerUdDeen** [comment]
Now let me know if it is possible to use java-cloudant for the offline first (java-SE) application.
if this library(java-cloudant) provide offline first functionality linked some helping materila or sample project that should include.
   1.Database creation
   2. CRUD
   3. replication with offline database and cloudant.
Thanks.

**Comment by ZaheerUdDeen** [comment]
By creating another project and doing everything fresh the above error has been managed, but unfortunately, the following error started arising.

This is the code what I am trying to do is. (As below)
![image](https://user-images.githubusercontent.com/11150958/33953164-e7b440ae-e055-11e7-9be4-fc3b2530fa88.png)

Below is the error that is arising.
![image](https://user-images.githubusercontent.com/11150958/33953221-12fc0d00-e056-11e7-97b3-1faefe183767.png)
![image](https://user-images.githubusercontent.com/11150958/33953295-4ef95de4-e056-11e7-9a07-58864c3520f4.png)

**Comment by ricellis** [comment]
Re: [this comment](https://github.com/cloudant/sync-android/issues/559#issuecomment-351458824)

I will try to clarify the differences between `java-cloudant` and `sync-android`, both of these projects use the Java language and can run in Java SE.

The `cloudant-client` from [java-cloudant](https://github.com/cloudant/java-cloudant) provides Java APIs for interacting with a remote Cloudant server - it has no local datastore so has no built-in offline first capability. If you wanted to write an offline first application using java-cloudant's cloudant-client alone then you would have to write all the local database and replication functionality yourself.

The `cloudant-sync` artifacts from this (sync-android) repository are code for creating and managing local databases and establishing replications between the local databases and the remote Cloudant. The artifacts are published for both Android and JavaSE. If you want to develop an offline first application then the sync-android JavaSE dependency (`group: 'com.cloudant', name: 'cloudant-sync-datastore-javase'`) is the best one to use.

**Comment by ZaheerUdDeen** [comment]
Hey Guys Great, Everything working now on >javaSE.

One more help, under this thread.
How can I create a database on cloudant server using >sync-android programmatically? 
what now I am doing is:
   I am manually creating a database(>tasks) on cloudant server. Then I put my database name here (As below) ![image](https://user-images.githubusercontent.com/11150958/34010713-81ef14a8-e12f-11e7-949c-95a0ec230754.png) to replicate the local document store with an online database that I just created in cloudant server.

But what actually I wanted to do is, to create the database on cloudant server programmatically and then replicate both the local document store and online database in cloudant server.

**Comment by ricellis** [comment]
Since sync-android is designed for on device we recommend that it does not have Cloudant admin credentials, but rather uses something like an API key with replicator permission. Since an API key can only be generated once a database exists and a database can only be created by admins we do not provide a programmatic API in sync-android for creating a database to discourage the client side storage of admin credentials.

Usually sync-android users would run another server based application to have a sign-up or similar that creates the necessary Cloudant server side resources.

If you really need to create Cloudant databases from the device, and understand the security risks inherent in storing admin creds on the device, then you can [create a database by making a HTTP request to Cloudant's HTTP API](https://console.bluemix.net/docs/services/Cloudant/api/database.html#create) or using a library like java-cloudant alongside sync-android to do so. For example you could add the java-cloudant `group: 'com.cloudant', name: 'cloudant-client'` also to your application and use its [createDB](https://static.javadoc.io/com.cloudant/cloudant-client/2.11.0/com/cloudant/client/api/CloudantClient.html#createDB-java.lang.String-) method.

**Comment by tomblench** [comment]
closing, no further action
