### ISSUE TITLE
Can I synchronise desired documents without synchronise whole database ?

### ISSUE THREAD

**Issue by ZaheerUdDeen** [cloudant/sync-android#561]
- Using sync-android library can I synchronize a specific number of documents the database.
- For example
    - My JavaSE application uses some different documents and my android application interact with different documents of the same database in the cloudant server.

If so, please refer me the guideline.

Thanks.

**Comment by ricellis** [comment]
You can use filters with pull or push replication to control which documents are replicated.

For pull replication see:
* [Filtered pull replication](https://github.com/cloudant/sync-android/blob/master/doc/replication.md#filtered-pull-replication)
* [`ReplicatorBuilder.Pull#filter(PullFilter)`](https://static.javadoc.io/com.cloudant/cloudant-sync-datastore-android/2.0.2/com/cloudant/sync/replication/ReplicatorBuilder.Pull.html#filter-com.cloudant.sync.replication.PullFilter-)
* [`PullFilter`](https://static.javadoc.io/com.cloudant/cloudant-sync-datastore-android/2.0.2/com/cloudant/sync/replication/PullFilter.html)

For push replication see:
* [`ReplicatorBuilder.Push#filter(PushFilter)`](https://static.javadoc.io/com.cloudant/cloudant-sync-datastore-android/2.0.2/com/cloudant/sync/replication/ReplicatorBuilder.Push.html#filter-com.cloudant.sync.replication.PushFilter-)
* [`PushFilter`](https://static.javadoc.io/com.cloudant/cloudant-sync-datastore-android/2.0.2/com/cloudant/sync/replication/PushFilter.html)

**Comment by tomblench** [comment]
closing, no further action

**Comment by tomblench** [comment]
@ZaheerUdDeen please re-open if you still have questions on this
