### ISSUE TITLE
Offline Document Store creation not working by running distributable Jar.

### ISSUE THREAD

**Issue by ZaheerUdDeen** [cloudant/sync-android#570]
I am using this library for JavaFX desktop application.

- By running application From IDE(NetBeans, Eclipse) everything working perfectly.
- But after creating a jar file of the application.
    -No offline document is been created for offline synchronization.
    - Below is the exact line where the program stuck
             DocumentStore ds = DocumentStore.getInstance(new File(path, "my_document_store"));
             In my case:
                    path=new File(System.getProperty("user.dir"));

The Same issue exists after creating ant built the distributable .exe package for deploying on different window systems.

**Comment by tomblench** [comment]
I suggest you add logging (see https://github.com/cloudant/sync-android/blob/master/doc/logging.md) to your deployed application and examine the logs to see what is going wrong.

Or you could modify your deployed program so that it generates extra output (to the console or a file) which will help us pinpoint exactly what is going wrong.

Your issue may be a problem with our library, or it may be a bug in your code, or a problem with the environment or configuration of your application. At the moment, and without extra information, we can't tell which it is.

**Comment by ZaheerUdDeen** [comment]
HI,  I have got some findings. Hope these will help.

1. Below is the log Console output when i run my application from Netbeans and every working perfectly.
 
![netbeanseconsole](https://user-images.githubusercontent.com/11150958/35914434-153e5ae6-0c25-11e8-8a1e-993771c021ee.PNG)
![netbeanseconsole1](https://user-images.githubusercontent.com/11150958/35914451-1e8c4b3a-0c25-11e8-95ef-66d089791349.PNG)

2. Now This is the output when I run the application by executing Application.jar file through windows command prompt.
![consoleaferrunningjar](https://user-images.githubusercontent.com/11150958/35914512-536d1fd2-0c25-11e8-88d3-50c4969369e0.PNG)


Now the underlined bluelines of both output are same but the deference comes after the red line.

**Comment by tomblench** [comment]
We don't have any experience of running on Windows but apart from the `[SEVERE] null` and `instantiated [null]` log messages, everything else looks fine.

In your first example it looks like 6 documents were pushed to your remote server, did you check on the remote side to see that those documents had been pushed?

**Comment by ZaheerUdDeen** [comment]
Yes in the first case(when I run the application through IDE i.e Netbeans or eclipse) everything working fine. 

but when i create .jar file and deployable package it creates problem.

**Comment by tomblench** [comment]
I suspect your deployed jar is having trouble locating the native DLL for sqlite4java

**Comment by ZaheerUdDeen** [comment]
Let me tell the whole story.

I am using [java-cloudant](https://github.com/cloudant/java-cloudant) to create the database only for the first time  when a user creates an account.

Then i am using [sync-android](https://github.com/cloudant/sync-android) to use this database with offline first approach.

Now when I run my application form IDE everything working perfectly both java-cloudant and sync-android. 

after creating .jar file the database is created perfectly which is done through java-cloudant, but applicaiton is not creating offline store which is done by sync-android library. 


This  is the exact line which is not working.
DocumentStore ds = DocumentStore.getInstance(new File(path, "my_document_store"));

Did this library is checked after creating and ruining jar files?

**Comment by ZaheerUdDeen** [comment]
yes, I suspect that too, Let me do homework to find some solution.

**Comment by ZaheerUdDeen** [comment]
Exactly that was the issue. when I manually copy native DLL for sqlite4java in library folder where sqlite4java.jar exists everything works fine. thanks.
