### ISSUE TITLE
Improve documentation for replication policies

### ISSUE THREAD

**Issue by tomblench** [cloudant/sync-android#572]
[Bryn's document](https://github.com/cloudant/sync-android/blob/master/doc/replication-policies.md) is very comprehensive but a bit confusing and a little overwhelming for first-time users.

As per #568 there are some gotchas setting up periodic replications.

Actions we should do under this issue:
- Merge in the sample code in Bryn's `freestyle-example-app` branch. This should be a simple variant of the "Todo" sample app which uses the JobService variant or the ReplicationService variant.
- Clarify the "Replication Policies" document with more obvious "recipes"

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/sync-android/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
