### ISSUE TITLE
Add support for for _doc_ids filter in Pull replicator

### ISSUE THREAD

**Issue by yhilem** [cloudant/sync-android#578]
Thanks for your hard work,
Can you please add support for for _doc_ids filter in Pull replicator ?
Ref : http://docs.couchdb.org/en/2.1.1/api/database/changes.html#doc-ids

Thanks
Youcef HILEM

**Comment by emlaver** [comment]
We don't have plans to support this but will consider and prioritize this item against our other work across all of our libraries.  
An alternative option is to consider using a [filtered pull replication](https://github.com/cloudant/sync-android/blob/master/doc/replication.md#filtered-pull-replication), but it may not be as efficient on the server side for larger databases.

**Comment by tomblench** [comment]
@yhilem we're aware of how to do it, it just isn't a priority in the backlog of work we have across all of the libraries we support.
