### ISSUE TITLE
TodoSync app needs updating for later versions of Gradle etc

### ISSUE THREAD

**Issue by acutetech** [cloudant/sync-android#584]
Initially the Todo sample app would not build for me. I followed tips from Android Studio, until the errors went and it built (and ran OK). When finished, I observed the following differences:

(1) In build.gradle: 
    classpath 'com.android.tools.build:gradle:3.1.4'
    compileSdkVersion 27
    buildToolsVersion '27.0.3'
    I changed instrumentTest.setRoot('tests') -> androidTest.setRoot('tests')
    I changed compile ->implementation (twice)

(2) In gradle-wrapper.properties
    distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip

I suggest this is thoroughly checked and updated in Github

**Comment by rajinib** [comment]
@acutetech Please open a pull request containing the changes outlined.
