### ISSUE TITLE
Question: reading arbitrary JSON objects

### ISSUE THREAD

**Issue by acutetech** [cloudant/sync-android#588]
Please excuse another Newbie question - this time on the Read operation: how can I read an arbitrary JSON document?

Your TODO sample app and CrudSamples use a "flat" document structure, from which each element can be extracted  like this:
```
Map<String, Object> map = rev.getBody().asMap();
String type =  map.get("type"));
```

How do I get an object if it is not flat? My document is of the form:
```
"v": {
    "address": "00:02:5B:00:66:77",
    "endReminder": false,
    "startTime": 60
  }
```
map.get("v").toString() gives  this (note no quotes so can't be treated as JSON):
`{address=00:02:5B:00:15:20, endReminder=false, startTime=60}`

On the other hand, rev.getBody().asBytes() gives this:
`{"v":{"address":"00:02:5B:00:15:20","endReminder":false,"startTime":60}}`

from which I can use substring() to give me the following JSON string:
`{"address":"00:02:5B:00:15:20","endReminder":false,"startTime":60}`

which I can finally convert into a Java object (in this case using Gson) like this (where 'v' is the JSON string from the previous line):
```
 Gson gson = new Gson();
 ReminderRecord reminderRecord = gson.fromJson(v, ReminderRecord.class);
```
This works for me but feels inelegant (and my CouchDB document is still very simple). Is there a general way of obtaining Java objects from an arbitrarily complex JSON document body?

**Comment by ricellis** [comment]
As you have seen the sync-android `DocumentRevision` gives you the option of retrieving the document body as the raw `byte[]` or as a `Map<String, Object>` (which is about the closest Java type to a JSON object without importing another library).

When using the `Map<String, Object>` form if the document is not flat you can just extract a value into another `Map` by casting e.g.
```java
Map<String, Object> map = rev.getBody().asMap();
Map<String,Object> v =  (Map<String, Object>) map.get("v"));
String address = (String) v.get("address");
```
This requires you to know what types you are expecting or to do some instance checks or other introspection to determine the types. The advantage is that the `Map` allows for completely arbitrary JSON.

Alternatively use the `byte[]` with your preferred deserializer (I guess Gson). In that case you can deserialize into a model type as in your example. Note that you can use additional classes to represent nested JSON objects e.g.:
```java
    class Doc {
        public ReminderRecord v;
    }
    class ReminderRecord {
        public String address;
        public boolean endReminder;
        public long startTime;
    }
Doc d = gson.fromJson(new String(rev.getBody().asBytes(), "UTF-8"), Doc.class);
ReminderRecord reminderRecord = d.v;
```
This approach ties in nicely with POJOs, but lacks flexibility in that it will only deserialize into the model fields, so isn't as flexible for arbitrary content (although you can deserialize into fields of "arbitrary" types like `Map`.

or you can deserialize into something like Gson's built-in `JsonObject` for arbitrary JSON e.g.
```java
JsonObject doc = gson.fromJson(new String(rev.getBody().asBytes(), "UTF-8"), JsonObject.class);
JsonObject reminderRecord = doc.getAsJsonObject("v");
```
This is very similar to the `Map<String, Object>` but approach, but you can use Gson's utilities for doing the type checking and casting of the fields (e.g. `getAsJsonObject`).

Which route you choose will depend on the needs of your application, for example, whether you have a complete model that you can use or whether you need to use one-size-fits-all objects like `Map` or `JsonObject`.

By the way the `map.toString()` is Java's default formatting for printing a `Map`, it knows nothing about JSON it is simply a key=value mapping, hence the reason it is not valid JSON.

Hope that helps.
