### ISSUE TITLE
_local document has been replicated

### ISSUE THREAD

**Issue by acutetech** [cloudant/sync-android#589]
In my PouchDB days I used a _local document to store soem settings. My understanding was that documnts with an id starting with "_local" would stay on the device and not be sent to the server. This does not seem to be the case with sync-android.

In my Cloudant dashboard I see the following document, which  I think should not have arrived there:

```
{
 "id": "_local/role",
 "key": "_local/role",
 "value": {
  "rev": "28-207d4e0441b94e8ca130d1ec338a9d43"
 },
 "doc": {
  "_id": "_local/role",
  "_rev": "28-207d4e0441b94e8ca130d1ec338a9d43",
  "role": "receiver"
 }
}
```
I have checked: if I change this document on my local device then do a push-sync, it changes at the server. Unlike the other documents, I do not seem to be able to edit this document at the server, so I have not (yet) been able to conduct the reverse experiment - to see if it is replicated from the server to the device.

In the database created by PouchDB, there is no sign of the _local/role document.

Am I missing something here, or is this a bug?

**Comment by ricellis** [comment]
sync-android doesn't expose API methods for writing `_local` documents on the `Database` interface. Prefixing an id with `_local` is insufficient to get the behaviour of a CouchDB local document hence the reason it slips through into the replication.

There are internal methods used to write local documents for replication checkpoints only, but they rely on a different document class (`LocalDocument` vs `DocumentRevision`) and get written and read via different code paths to a separate table in the underlying SQL database.

So there isn't really a replication bug, the real local documents in sync-android don't get replicated, but it ought to be more clear both in documentation and probably via exception that writing a `DocumentRevision` with a `_local` prefix won't work.

**Comment by acutetech** [comment]
Hmmm.... So is this LocalDocument functionality available to users, or only for your internal use? I started along these lines:

```
            String id = "_local/role";
            Map<String, Object> map  = new HashMap<String, Object>();
            map.put("role", payload);
            map.put("androidId", mAndroidId);

            DocumentBody body = DocumentBodyFactory.create(map);
            LocalDocument localDoc = new LocalDocument(id, body);

            // Now place it in the local database
            LocalDocument created = mDocumentStore.database().create(localDoc);
```
which starts OK, but fails at the last line. 

Are there user-facing CRUD methods for LocalDocument? If not I guess I make use of other Android storage options.

(BTW, I now seem to have a _local/role document on the server which I can't delete from the Cloudant dashboard. Is it safe there? Is there any chance it will be pushed down to devices?)

A final thought: is there any danger if I continue to use a document with a "_local" id? It does seem to work (locally), but gives conflicts at the server....

**Comment by ricellis** [comment]
FYI I have raised https://github.com/apache/couchdb/issues/1628 related to this.

**Comment by tomblench** [comment]
@acutetech #591 has merged which now allows you to use the existing public API methods on `Database`, namely `read`, `contains`, `create`, `delete`, to manipulate local documents in the manner you originally described.

You can use a snapshot build to try this out, or wait until the next official release.

**Comment by acutetech** [comment]
When the problem surfaced I stopped using _local documents and switched to using Android's SharedPreferences mechanism, which seems a satisfactory alternative.

Good that you have dealt with the issue, though.  I trust there will be appropriate user-facing documentation for the next release. Thanks.

**Comment by tomblench** [comment]
OK no problem.
