### ISSUE TITLE
QueryResult Iterating is too slow - Performance Issue

### ISSUE THREAD

**Issue by Fenil15** [cloudant/sync-android#596]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
I have a CouchDB database which have over 13000 documents synced locally (This is just test data, actual data will go up further). Running a simple mango query locally and iterating over the results is taking too much time.

Here is the the simple query, where oQueryMap has simple 3-4 keys added for matching -
`oQueryResult = this.mDocumentStore.query().find(oQueryMap,skip,limit,null,null);`

The above query is excuted very quickly, less than a sec. But then, when I am iterating over its results using below sample code, it is taking too much time around more than 1 min.

```java
for (DocumentRevision rev : oQueryResult) { ... }
```

The above query result is matched with just 4 documents returned. Average size of these documents is around 3-4KB. But most of the document sizes is less than 1KB. Is there any way to optimize this, since as per the current time required for execute query it is as good as non usable?
Our backend uses Couchdb server v2.3.3

### 2. What you expected to happen
Expected the result response to be less than 2secs
### 3. What actually happened
Result response is taking more than 60 secs (In some cases and devices even more than that)
## Environment details
- Version(s) that are affected by this issue.
    - `2.3.1-SNAPSHOT`
- Android or Java version (including vendor and platform)
    - Pixel 2 device, Android 9, API level 28, Linux/armv64l
    - Samsung J5 device, Android 7, API level 24, Linux/armv64l
- sync-android artifact you are using:
    - [ ] cloudant-sync-datastore-android-encryption

**Comment by ricellis** [comment]
Have you [created an index](https://github.com/cloudant/sync-android/blob/master/doc/query.md#creating-indexes) for the document keys you want to match against?
Do you see this log warning message?
```
query could not be executed using indexes alone; falling back to filtering documents themselves. This will be VERY SLOW as each candidate document is loaded from the datastore and matched against the query selector.
```

**Comment by Fenil15** [comment]
@ricellis  - Thanks, after indexing the speed has been improved to less than 4 secs.

**Comment by Fenil15** [comment]
@ricellis - However after implementing indexing, still I am getting the below log warning message -
> query could not be executed using indexes alone; falling back to filtering documents themselves. This will be VERY SLOW as each candidate document is loaded from the datastore and matched against the query selector.

Any idea as to why I am getting this message as all the query parameters are already indexed?

**Comment by ricellis** [comment]
Not without more information.
Can you provide the call you are making to create the index and your query map and an example document?

**Comment by Fenil15** [comment]
@ricellis Haven't changed anything but the warning message dissappeared. Not sure what happened here, will update you in case I get the warning message. Thanks!
