### ISSUE TITLE
Where To find Api password from Credentials?

### ISSUE THREAD

**Issue by ZaheerUdDeen** [cloudant/sync-android#597]
To use android-sync sdk I need api-password to sync with the cloud DB.

**URI uri = new URI("https://apikey:### apipasswd@username.cloudant.com/my_database");
DocumentStore ds = DocumentStore.getInstance(new File(path, "my_datastore"));**

where to find Api-password from the given Cloudant Service Credentials
{
  "apikey": ...
  "host": ...
  "iam_apikey_description": ...
  "iam_apikey_name": ...
  "iam_role_crn": ...
  "iam_serviceid_crn": ...
  "url": ...
  "username": ...
}

Edit: Updated to protect account info

**Comment by emlaver** [comment]
@ZaheerUdDeen If you want database level access, can generate an API key in the Cloudant Dashboard to grant access to a specific database.  See Step 3 `Securing your database`: https://developer.ibm.com/recipes/tutorials/controlling-your-cloudant-databases-with-bluemix-api-connect/

If not, you should be able to generate credentials in the Cloudant service that contains a `username` and `password` to use basic auth e.g.
`https://username:password@username.cloudant.com`

Also, take a look at our sample app: https://github.com/cloudant/sync-android/tree/master/sample/todo-sync

**Comment by ZaheerUdDeen** [comment]
In a second case what would be the password? in the url: 
https://username:password@username.cloudant.com

**Comment by emlaver** [comment]
@ZaheerUdDeen When you create the Cloudant Service, there is a box called `Available authentication methods`.  If you selected `Use only IAM` then I believe you won't be able to get the needed legacy Basic auth credentials.  
You can either delete and re-create a new Cloudant service with the option `Use both legacy credentials and IAM` or create a support ticket asking for legacy auth to be enabled in your IBM Cloud account.

**Comment by ZaheerUdDeen** [comment]
Thanks A lot!
