### ISSUE TITLE
Entry name 'AndroidManifest.xml' collided

### ISSUE THREAD

**Issue by richard457** [cloudant/sync-android#603]
I am having issue using the dependency in android with the above error
- sync-android artifact you are using:
    - [ ] cloudant-sync-datastore-android
    - [ ] cloudant-sync-datastore-android-encryption
    - [ ] cloudant-sync-datastore-javase
-->

**Comment by emlaver** [comment]
Hello @richard457, can you please provide the error message and the versions of each artifact?

**Comment by enylton** [comment]
Hello.
My first time trying to add couldant-sync to an Android app. I'm also having this issue.

The error message is:
```
Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > Entry name 'AndroidManifest.xml' collided
```
I'm using _implementation 'com.cloudant:cloudant-sync-datastore-android-encryption:2.4.1'_

I was able to compile using _android.useNewApkCreator=false_, as pointed here:
[https://developer.android.com/studio/releases/gradle-plugin#zipflinger](https://developer.android.com/studio/releases/gradle-plugin#zipflinger)
