### ISSUE TITLE
SQLDatabaseQueue.submitTaskToQueue Error

### ISSUE THREAD

**Issue by zedherle** [cloudant/sync-android#604]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Bug Description
We wanted to know what is the reason behind this error we get often. Couldn't figure this out yet!

SQLDatabaseQueue.java line 175
com.cloudant.sync.internal.sqlite.SQLDatabaseQueue.submitTaskToQueue

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

This happens when we actually query. But we can't give you the exact reproducible steps. We wanted to what could have happened. 

### 2. What you expected to happen

We want to avoid these exceptions

### 3. What actually happened

We are getting these exceptions quiet often.  

## Environment details

- Version(s) that are affected by this issue.
    > 2.0.2
- Android or Java version (including vendor and platform)
    > Android 5.1, API level 22, Linux/armv7l
    > Java 1.8.0_151 OpenJDK macOS
- sync-android artifact you are using:
    - [ ] cloudant-sync-datastore-android

**Comment by mojito317** [comment]
Hello @zedherle!  I suspect that the queue is being shutdown by `com.cloudant.sync.documentstore.Database#close()` before the queue task can actually happen.

If not, then please provide me the actual stack trace.

**Comment by zedherle** [comment]
```
com.cloudant.sync.internal.sqlite.SQLDatabaseQueue.submitTaskToQueue (SQLDatabaseQueue.java:175)
com.cloudant.sync.internal.sqlite.SQLDatabaseQueue.submit (SQLDatabaseQueue.java:110)
com.cloudant.sync.internal.query.IndexUpdater.updateMetadataForIndex (IndexUpdater.java:164)
com.cloudant.sync.internal.query.IndexUpdater.updateIndex (IndexUpdater.java:143)
com.cloudant.sync.internal.query.IndexUpdater.updateIndex (IndexUpdater.java:111)
com.cloudant.sync.internal.query.IndexUpdater.updateAllIndexes (IndexUpdater.java:98)
com.cloudant.sync.internal.query.IndexUpdater.updateAllIndexes (IndexUpdater.java:72)
com.cloudant.sync.internal.query.QueryImpl.refreshAllIndexes (QueryImpl.java:207)
com.cloudant.sync.internal.query.QueryImpl.find (QueryImpl.java:223)
com.cloudant.sync.internal.query.QueryImpl.find (QueryImpl.java:212)
com.miairline.data.dao.CloudantBaseDao.getElementsByRule (CloudantBaseDao.java:173)
com.miairline.data.dao.StockDao.getAllStockList (StockDao.java:41)
com.miairline.data.repository.StockListRepository$1.subscribe (StockListRepository.java:69)
io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual (ObservableCreate.java:40)
io.reactivex.Observable.subscribe (Observable.java:12025)
io.reactivex.Observable.subscribe (Observable.java:12011)
io.reactivex.Observable.subscribe (Observable.java:11889)
com.miairline.data.repository.CloudantRepository.initRepositoryData (CloudantRepository.java:255)
com.miairline.data.repository.StockMutationRepository$2.subscribe (StockMutationRepository.java:215)
io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual (ObservableCreate.java:40)
io.reactivex.Observable.subscribe (Observable.java:12025)
io.reactivex.internal.operators.observable.ObservableObserveOn.subscribeActual (ObservableObserveOn.java:45)
io.reactivex.Observable.subscribe (Observable.java:12025)
io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run (ObservableSubscribeOn.java:96)
io.reactivex.Scheduler$DisposeTask.run (Scheduler.java:571)
io.reactivex.internal.schedulers.ScheduledRunnable.run (ScheduledRunnable.java:66)
io.reactivex.internal.schedulers.ScheduledRunnable.call (ScheduledRunnable.java:57)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201 (ScheduledThreadPoolExecutor.java:152)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:265)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:818)
```

**Comment by mojito317** [comment]
Hi @zedherle!
I only can say to make sure the `QueryImpl.close()` hasn't been called on the same instance before you run a query `QueryImpl.find()`.

**Comment by zedherle** [comment]
ok. thanks. We will check.

**Comment by ricellis** [comment]
FWIW `QueryImpl.close()` is an internal method that should not be called by application code. However, it is called as part of the [`DocumentStore#close()`](https://www.javadoc.io/static/com.cloudant/cloudant-sync-datastore-core/2.4.0/com/cloudant/sync/documentstore/DocumentStore.html#close--) procedure, so you should validate that isn't being called before calling [`Query#find()`](https://www.javadoc.io/static/com.cloudant/cloudant-sync-datastore-core/2.4.0/com/cloudant/sync/query/Query.html#find-java.util.Map-).
