### ISSUE TITLE
Mazha incorrectly encodes database paths

### ISSUE THREAD

**Issue by mikerhodes** [cloudant/sync-android#68]
If someone is proxying to Couch/Cloudant, they might well be using something like:
    
    https://dev.myserver.com/api/couch/account_2128459498a75498

Which ends up being:

    https://dev.myserver.com/api%2Fcouch%2Faccount_2128459498a75498

Because of:

https://github.com/cloudant/sync-android/blob/master/sync-core/src/main/java/com/cloudant/mazha/CouchURIHelper.java#L65

We need to figure out how to allow arbitrary paths, rather than assuming a `https://host.com/db_name` structure.

**Comment by emce** [comment]
ETA?

**Comment by mikerhodes** [comment]
I'm afraid there isn't one as yet, we're heads down on a couple of required features for at least the next couple of weeks.

**Comment by rhyshort** [comment]
Sorry for not keeping this ticket up to date, we fixed this issue. If you upgrade to the latest version, this use case should work for you.
