### ISSUE TITLE
Extending QueryBuilder

### ISSUE THREAD

**Issue by emce** [cloudant/sync-android#71]
I would be fine to extend QueryBuilder class by "negative" method, I mean: notEqualTo, notOneOf, etc.

**Comment by mikerhodes** [comment]
Could you provide a couple of examples of the documents and queries that would match them using the operators you propose? It's easier for me to understand that way :)

**Comment by emce** [comment]
for example if you have states for your entities in db, and you want to fetch all but not deleted,so:
``` query.index("default").notEqualTo(4); ```
or, if you want to fetch not active state entities:
``` query.index("default").notOneOf(1, 2, 3); ```

**Comment by mikerhodes** [comment]
Okay, we will cover at least `notEqualTo` in the port of Cloudant Query that's currently in progress (started in #72 and #74).

Hopefully we'll eventually implement `notOneOf` as we increase the number of features in both Query for iOS and Android.

**Comment by mikerhodes** [comment]
(And the Query port will supersede the current `sync.indexing` package)

**Comment by rhyshort** [comment]
Query has now completly replaced the `sync.indexing` package and has been removed. Let us know if you have any issues using query for your use case eg missing operators.
